--- 
- 
  connection: local
  gather_facts: false
  hosts: windows
  tasks: 
    - 
      block: 
        - 
          name: "determine hosts that are up"
          vars: 
            ansible_connection: ssh
          wait_for_connection: 
            timeout: 5
        - 
          group_by: 
            key: running_hosts
          name: "add devices with connectivity to the \"running_hosts\" group"
      rescue: 
        - 
          debug: 
            msg: "cannot connect to {{ inventory_hostname }}"
- 
  gather_facts: false
  hosts: running_hosts
  tasks: 
    - 
      command: date
