--- 
- hosts: windows
  connection: local
  gather_facts: no
  tasks:
  - block:
    - name: determine hosts that are up
      wait_for_connection:
        timeout: 5
      vars:
        ansible_connection: ssh
    - name: add devices with connectivity to the "running_hosts" group
       group_by:
         key: "running_hosts"
    rescue:
    - debug: 
        msg: "cannot connect to {{ inventory_hostname }}"

- hosts: running_hosts
  gather_facts: no
  tasks:
  - command: date
